name: Create PDF on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y pandoc texlive

    - name: Convert Markdown to PDF
      run: pandoc '*'.md -o output.pdf

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-pdf
        path: output.pdf
